data:
    root_dir: /home/ykli/workspace/dataset/ai_challenger_scene
    train:
        im_dir: scene_train_images_20170904
        annotation: scene_train_annotations_20170904.json
    val:
        im_dir: scene_validation_images_20170908
        annotation: scene_validation_annotations_20170908.json
    test:
        im_dir: scene_test_a_images_20170922

    trainsplit: train
    scale_size: 512
    img_size: 448
    crop: False
    rand_size_crop: False
model:
    arch: Baseline_v1
    conv_arch: densenet_places
    pooling: True
    dilation: 2
    dropout: 0.3


logs:
    dir_logs: output/Scene/baseline_v2
optim:
    batch_size: 256
    lr: 0.01
    lr_decay: 0.3
    lr_decay_epoch: 5
    weight_decay: 0.0005
    epochs: 40
    eval_epochs: 5
